### ISSUE TITLE
callback contain no result Gas required exceeds limit: 3000000

### ISSUE THREAD

**Issue by smatthewenglish** [stonecoldpat/anonymousvoting#13]
<img width="1238" alt="screen shot 2017-08-23 at 10 22 35 am" src="https://user-images.githubusercontent.com/9053984/29620877-30506160-87ed-11e7-9bdd-b6f5618dcbde.png">

I was trying to deploy this contract to ropsten using remix and meta mask, but I ran into the error `callback contain no result Gas required exceeds limit: 3000000`.

**Comment by stonecoldpat** [comment]
I'm surprised you got the code to load in remix! It always froze for me! 

I remember creating the contract required around 3.7m gas. I'd recommend setting the gas limit to 4.7m and then deploy it. That error is saying the gas limit in remix is set to 3m (which isn't enough).

**Comment by s-matthew-english** [comment]
It seems to break even with a higher gas limit, I put some additional details here: 

https://medium.com/@s.matthew.english/smart-contract-deployment-dame-mas-gasolina-ddf8ca792e

**Comment by stonecoldpat** [comment]
Hey. 

I recommend using Ethereum wallet for deploying contracts. Remix doesn't like big contracts like this one. I put it in Ethereum wallet and it is estimating 4,619,006 gas:

<img width="550" alt="screen shot 2017-08-23 at 16 21 53" src="https://user-images.githubusercontent.com/6450946/29623800-7266d912-881f-11e7-9032-ec6fc1fbb4c1.png">

It also caught two "unused variables" which might stop it compiling. This is because Solidity has had an update where it won't let you deploy contracts with unused variables. Easy fix is just re-assigning the variable to itself. i.e. bit = bit. The variables are used but inside the assembly {} brackets which Solidity compiler seems to ignore.

**Comment by stonecoldpat** [comment]
I just updated AnonymousVoting.sol to do the re-assignment. Maybe that is what remix was really complaining about.

**Comment by SamuelRoberts96** [comment]
I am also getting an error when trying to run it.

![image](https://user-images.githubusercontent.com/42743618/62218435-5a26a000-b3a4-11e9-932c-a49afe843772.png)

This is the error:
![image](https://user-images.githubusercontent.com/42743618/62218520-87734e00-b3a4-11e9-832e-826ff27c9c0b.png)

Then it simply fails.
I am using remix connected to MetaMask.
